# Generated by Django 6.0.4 on 2026-04-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyderabadjobs',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
