# Generated by Django 6.0.4 on 2026-04-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_alter_hyderabadjobs_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyderabadjobs',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
