# Generated by Django 6.0.4 on 2026-04-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_alter_hyderabadjobs_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BangloreJobs',
            new_name='BangaloreJobs',
        ),
    ]
