# Generated by Django 6.0.4 on 2026-04-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_rename_banglorejobs_bangalorejobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangalorejobs',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='chennaijobs',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
